### ISSUE TITLE
10번 라인 이미지 깨져보여요!

### ISSUE THREAD

**Issue by dearjsmc4** [sooyoungjeong/web-basic#1]
https://github.com/sooyoungjeong/web-basic/blob/master/Hyunjun/index.html

로고 이미지같은데 경로 문제때문에 이미지가 깨져보이네요
그 외엔 잘 하신 것 같아요!
탭 이름 부분에 아이콘 작게 넣으신 거 신기하네요!

**Comment by Dallmoon** [comment]
파일 경로 상에 한글이 포함되어서 또는 파일 위치가 변경되어서, 둘 중 하나로 보입니다. 수정완료했습니다!
