### ISSUE TITLE
새로운 페이지를 만드신 건가요?

### ISSUE THREAD

**Issue by dearjsmc4** [sooyoungjeong/web-basic#2]
https://github.com/sooyoungjeong/web-basic/blob/master/sooyoung/sooyoung.html

언스플래쉬 사이트 레이아웃을 따서 새로운 컨텐츠를 넣으신건가요?
고양이 너무 귀여워요.
정렬이나 버튼 알맞게 넣으신 것도 좋아요.

**Comment by isIntegerZero** [comment]
넵 ㅎㅎ 비슷한 구성으로 다르게 만들어봤습니다.
유순님 코드 따라서 저도 사진에 테이블 태그를 적용해봐야겠어요 ㅎㅎ
